n = input('digite algo:')
print(n.isnumeric(),'numero')
print(n.isalpha(),'letra')
print(n.isprintable(),'impresso')
print(n.islower(),'minuscula')
print(n.isupper(),'maiuscula')
print(n.isalnum(),'alfanumerico')
print(n.isascii(),'ascii')
print(n.isdecimal(),'decimal')
print(n.isdigit(),'digito')
print(n.isidentifier(),'?')
print(n.istitle(),'titulo')
